name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: yarn install --frozen-lockfile
      # Prepack so the linter and tests have access to the build exports of
      # other packages' prepack.
      - run: yarn workspaces run prepack
      - run: yarn lint
      - run: yarn test
      - run: yarn docs
